<a href="https://colab.research.google.com/github/asarzina/mlbookcamp-homework/blob/main/Mlbookcamp_Homework_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd


In [3]:
np.__version__

'1.19.5'

In [4]:
pd.__version__

'1.1.5'

In [6]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2021-09-12 13:56:29--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv’

data.csv            100%[===================>]   1.41M  --.-KB/s    in 0.06s   

2021-09-12 13:56:29 (22.8 MB/s) - ‘data.csv’ saved [1475504/1475504]



In [48]:
df = pd.read_csv('data.csv')
df

Make       Model  Year  ... city mpg  Popularity   MSRP
0          BMW  1 Series M  2011  ...       19        3916  46135
1          BMW    1 Series  2011  ...       19        3916  40650
2          BMW    1 Series  2011  ...       20        3916  36350
3          BMW    1 Series  2011  ...       18        3916  29450
4          BMW    1 Series  2011  ...       18        3916  34500
...        ...         ...   ...  ...      ...         ...    ...
11909    Acura         ZDX  2012  ...       16         204  46120
11910    Acura         ZDX  2012  ...       16         204  56670
11911    Acura         ZDX  2012  ...       16         204  50620
11912    Acura         ZDX  2013  ...       16         204  50920
11913  Lincoln      Zephyr  2006  ...       17          61  28995

[11914 rows x 16 columns]

In [51]:
dfBmw = df.loc[df['Make'] == 'BMW']
dfBmw

Make       Model  Year  ... city mpg  Popularity    MSRP
0      BMW  1 Series M  2011  ...       19        3916   46135
1      BMW    1 Series  2011  ...       19        3916   40650
2      BMW    1 Series  2011  ...       20        3916   36350
3      BMW    1 Series  2011  ...       18        3916   29450
4      BMW    1 Series  2011  ...       18        3916   34500
...    ...         ...   ...  ...      ...         ...     ...
11901  BMW          Z4  2016  ...       22        3916   49700
11902  BMW          Z4  2016  ...       17        3916   66350
11903  BMW          Z8  2001  ...       12        3916  128000
11904  BMW          Z8  2002  ...       12        3916  130000
11905  BMW          Z8  2003  ...       12        3916  131500

[334 rows x 16 columns]

In [52]:
dfBmw.MSRP.mean()

61546.76347305389

In [53]:
df15 = df.loc[df['Year'] >= 2015]
df15

Make       Model  Year  ... city mpg  Popularity   MSRP
32     FIAT  124 Spider  2017  ...       26         819  27495
33     FIAT  124 Spider  2017  ...       26         819  24995
34     FIAT  124 Spider  2017  ...       26         819  28195
41      BMW    2 Series  2016  ...       23        3916  32850
42      BMW    2 Series  2016  ...       23        3916  38650
...     ...         ...   ...  ...      ...         ...    ...
11898   BMW          Z4  2015  ...       17        3916  56950
11899   BMW          Z4  2015  ...       17        3916  65800
11900   BMW          Z4  2016  ...       17        3916  57500
11901   BMW          Z4  2016  ...       22        3916  49700
11902   BMW          Z4  2016  ...       17        3916  66350

[5995 rows x 16 columns]

In [57]:
df15.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        0
Engine HP              51
Engine Cylinders        8
Transmission Type       0
Driven_Wheels           0
Number of Doors         5
Market Category      1324
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [70]:
print(round(df15['Engine HP'].mean()))

273


In [67]:
df15Filled = df15.fillna(df15['Engine HP'].mean())

In [71]:
print(round(df15Filled['Engine HP'].mean()))

273


In [73]:
dfRR = df.loc[df['Make'] == 'Rolls-Royce']
dfRR

Make                   Model  Year  ... city mpg  Popularity    MSRP
2921   Rolls-Royce                Corniche  2001  ...       10          86  359990
3505   Rolls-Royce                    Dawn  2016  ...       12          86  335000
5275   Rolls-Royce         Ghost Series II  2015  ...       13          86  286750
5276   Rolls-Royce         Ghost Series II  2015  ...       13          86  319400
5277   Rolls-Royce         Ghost Series II  2016  ...       13          86  295850
5278   Rolls-Royce         Ghost Series II  2016  ...       13          86  329325
5279   Rolls-Royce                   Ghost  2012  ...       13          86  250000
5280   Rolls-Royce                   Ghost  2012  ...       13          86  290000
5281   Rolls-Royce                   Ghost  2013  ...       13          86  296000
5282   Rolls-Royce                   Ghost  2013  ...       13          86  256650
5283   Rolls-Royce                   Ghost  2014  ...       13          86  263200
5284   Rolls-Royce                   Ghost  2014  ...       13          86  303300
7443   Rolls-Royce               Park Ward  2001  ...       11          86  259900
7444   Rolls-Royce               Park Ward  2002  ...       11          86  262990
7553   Rolls-Royce           Phantom Coupe  2014  ...       11          86  433550
7554   Rolls-Royce           Phantom Coupe  2015  ...       11          86  438325
7555   Rolls-Royce           Phantom Coupe  2016  ...       11          86  449525
7556   Rolls-Royce  Phantom Drophead Coupe  2014  ...       11          86  474600
7557   Rolls-Royce  Phantom Drophead Coupe  2015  ...       11          86  479775
7558   Rolls-Royce  Phantom Drophead Coupe  2016  ...       11          86  492000
7559   Rolls-Royce                 Phantom  2014  ...       11          86  402940
7560   Rolls-Royce                 Phantom  2014  ...       11          86  474990
7561   Rolls-Royce                 Phantom  2015  ...       11          86  407400
7562   Rolls-Royce                 Phantom  2015  ...       11          86  480175
7563   Rolls-Royce                 Phantom  2016  ...       11          86  417825
7564   Rolls-Royce                 Phantom  2016  ...       11          86  492425
9431   Rolls-Royce           Silver Seraph  2001  ...       11          86  219900
9432   Rolls-Royce           Silver Seraph  2002  ...       11          86  229990
11448  Rolls-Royce                  Wraith  2014  ...       13          86  284900
11449  Rolls-Royce                  Wraith  2015  ...       13          86  294025
11450  Rolls-Royce                  Wraith  2016  ...       13          86  304350

[31 rows x 16 columns]

In [79]:
dfRR1 = dfRR[['Engine HP', 'Engine Cylinders', 'highway MPG']].drop_duplicates()
dfRR1

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [93]:
X = dfRR1.to_numpy()
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [94]:
XT = X.T
XT

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [105]:
XTX = np.matmul(XT, X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [110]:
XTXinv = np.linalg.inv(XTX)
XTXinv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [107]:
np.matrix(XTXT).sum()

0.032212320677486125

In [109]:
y = [1000, 1100, 900, 1200, 1000, 850, 1300]
y

[1000, 1100, 900, 1200, 1000, 850, 1300]

In [111]:
XXX = np.matmul(XTXinv, XT)
XXX

array([[-0.00486592,  0.00336507, -0.00049461,  0.00143523, -0.00139492,
        -0.0023309 ,  0.00266407],
       [-0.19020088,  0.09362543, -0.08379139,  0.00491702,  0.22997159,
        -0.00609915, -0.02848958],
       [ 0.25164625, -0.13888652,  0.0729151 , -0.03298571, -0.09739786,
         0.07339609, -0.04480526]])

In [113]:
w = np.matmul(XXX, y)
w[0]

0.19989598183188978